Fixing some minor inconsistencies
buttercup/dossier pull request #7
Opened 2019-03-09 06:44 UTC by oscrx

Title says it all.

Love the project btw!

2019-03-11 12:54 UTC, perry-mitchell requested changes
1 minor change.. Looks great, thanks!

2019-03-11 12:54 UTC, perry-mitchell commented on roadmap/BUTTERCUP_BROWSER_EXTENSION.md
> + * Support for Opera
This can be removed - we won't be supporting Opera again.

2019-03-13 14:02 UTC, oscrx commented
All fixed now :)

2019-03-15 17:46 UTC, perry-mitchell approved these changes

2019-03-15 17:47 UTC, perry-mitchell commented
@oscrx Thanks!

2019-03-15 17:47 UTC, merged